### ISSUE TITLE
Correction problem. Command falls without execution. 

### ISSUE THREAD

**Issue by PolinaMuz** [milaboratory/minnn#190]
Hi, I am having this issue:
:/minnn correct --input /Users/log/extracted.mif  --output corrected.mif --groups UMI 
Counting sequences: 0%
Exception in thread "main" picocli.CommandLine$ExecutionException: Error while running command (com.milaboratory.minnn.cli.CorrectAction@63355449): java.lang.NullPointerException
	at picocli.CommandLine.execute(CommandLine.java:1051)
	at picocli.CommandLine.access$900(CommandLine.java:142)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:1246)
	at com.milaboratory.minnn.cli.Main$1.handle(Main.java:85)
	at com.milaboratory.minnn.cli.Main$1.handle(Main.java:68)
	at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1122)
	at com.milaboratory.minnn.cli.Main.handleParseResult(Main.java:90)
	at com.milaboratory.minnn.cli.Main.main(Main.java:62)
Caused by: java.lang.NullPointerException
	at com.milaboratory.minnn.correct.CorrectionAlgorithms.pass1ProcessRead(CorrectionAlgorithms.java:239)
	at com.milaboratory.minnn.correct.CorrectionAlgorithms.fullFileCorrect(CorrectionAlgorithms.java:72)
	at com.milaboratory.minnn.io.CorrectBarcodesIO.go(CorrectBarcodesIO.java:115)
	at com.milaboratory.minnn.cli.CorrectAction.run1(CorrectAction.java:64)
	at com.milaboratory.cli.ACommandWithSmartOverwrite.run0(ACommandWithSmartOverwrite.java:118)
	at com.milaboratory.cli.ACommand.run(ACommand.java:90)
	at picocli.CommandLine.execute(CommandLine.java:1043)
	... 7 more

**Comment by Alexander230** [comment]
Hi! What is minnn version? You can look it with minnn -v command. Also you can try to repeat the same extract and correct actions with minnn v 4.0.1 (latest version in master branch). And what was extract command to produce extracted.mif? Knowledge of extract pattern is important to reproduce the bug.

**Comment by PolinaMuz** [comment]
I have the latest version:
minnn -v
MiNNN v4.0.1 (built Fri Apr 19 15:51:51 MSK 2019; rev=44617ee; branch=release/v4.0.1; host=N2-Work)

And here is my command for mif extraction:
./minnn extract --input ./ampl_A_S45_R1_001.fastq.gz ./ampl_A_S45_R2_002.fastq.gz --output extracted.mif --pattern "^<aagcagtgGTATCAAcgcagagt$NNNNNNNNNN\*"

**Comment by Alexander230** [comment]
Thank you, I will check it to make better error message for this: there is no group UMI in the pattern, so correct command doesn't find it. Maybe, pattern should be like this:
"^<aagcagtgGTATCAAcgcagagt(UMI:NNNNNNNNNN)\*"
Also, $ sign is mark of the end of read, so it shouldn't be between nucleotides.

**Comment by PolinaMuz** [comment]
Hi, 
It worked, thank you.
However, now the same happens with minnn sort command.
What i did:
~./minnn extract --input ./ampl_A_S45_R1_001.fastq.gz ./ampl_A_S45_R2_002.fastq.gz --output extracted.mif --pattern "^<aagcagtgGTATCAAcgcagagt(UMI:NNNNNNNNNN)\\*"
~./minnn correct --input ./extracted.mif --output ./corrected-primary.mif --groups UMI
~./minnn sort --input ./corrected-primary.mif --output sorted.mif --groups UMI 
Reading: 0%
Reading: 11%  ETA: 00:01:50
Exception in thread "Thread-1" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at com.milaboratory.core.sequence.IO$NSequenceWithQualitySerializer.read(IO.java:144)
	at com.milaboratory.core.sequence.IO$NSequenceWithQualitySerializer.read(IO.java:133)
	at com.milaboratory.primitivio.PrimitivI.readObject(PrimitivI.java:105)
	at com.milaboratory.core.io.sequence.IO$SequenceReadSerializer.read(IO.java:54)
	at com.milaboratory.core.io.sequence.IO$SequenceReadSerializer.read(IO.java:24)
	at com.milaboratory.primitivio.PrimitivI.readObject(PrimitivI.java:105)
	at com.milaboratory.minnn.outputconverter.ParsedRead.read(ParsedRead.java:340)
	at com.milaboratory.minnn.io.IO$ParsedReadSerializer.read(IO.java:46)
	at com.milaboratory.minnn.io.IO$ParsedReadSerializer.read(IO.java:38)
	at com.milaboratory.primitivio.PrimitivI.readObject(PrimitivI.java:105)
	at com.milaboratory.minnn.io.MifReader.take(MifReader.java:151)
	at com.milaboratory.minnn.io.MifReader.take(MifReader.java:49)
	at cc.redberry.pipe.util.Chunk.readChunk(Chunk.java:63)
	at cc.redberry.pipe.CUtils$7.take(CUtils.java:323)
	at cc.redberry.pipe.CUtils$7.take(CUtils.java:315)
	at cc.redberry.pipe.blocks.O2ITransmitter.run(O2ITransmitter.java:66)
	at java.lang.Thread.run(Thread.java:748)
Writing: 0%

Processing time: 1,88m
Sorted 1000000 reads

**Comment by Alexander230** [comment]
Out of memory error can be solved in 2 ways:
1. Increase memory limit for java:
~./minnn -Xmx3000M sort --input ./corrected-primary.mif --output sorted.mif --groups UMI
3000M after -Xmx means 3000 megabytes, you can adjust this value to fit in computer memory.
2. Decrease sorting chunk size:
~./minnn sort --chunk-size 50000 --input ./corrected-primary.mif --output sorted.mif --groups UMI
Chunk size is specified in bytes. Too small values (lower than 10000) can lead to poor performance, and high values need more memory (-Xmx parameter may be needed).

**Comment by PolinaMuz** [comment]
Thank you very much, everything is fine now.
