### ISSUE TITLE
Extract fails on empty (too short?) reads

### ISSUE THREAD

**Issue by mikessh** [milaboratory/minnn#216]
Caused by: java.lang.IllegalStateException: Group start must be lower than the end. Start: 0, end: 0
        at com.milaboratory.minnn.pattern.Match.assembleGroups(Match.java:125)
        at com.milaboratory.minnn.cli.DescriptionGroups.addDescriptionGroups(DescriptionGroups.java:59)
        at com.milaboratory.minnn.io.ReadProcessor$ReadParserProcessor.process(ReadProcessor.java:392)
        at com.milaboratory.minnn.io.ReadProcessor$ReadParserProcessor.process(ReadProcessor.java:341)
        at cc.redberry.pipe.CUtils$9.process(CUtils.java:350)
        at cc.redberry.pipe.CUtils$9.process(CUtils.java:345)
        at cc.redberry.pipe.blocks.ParallelProcessor$Worker.run(ParallelProcessor.java:313)
        at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by Alexander230** [comment]
Short reads (even 1 nucleotide) are ok; empty will fail because of zero-length built-in group (R1, R2 etc). I will change this check to allow groups of zero length.

**Comment by Alexander230** [comment]
https://github.com/milaboratory/minnn/commit/394af11da822900a3d68c62f67a37a7b2ae4c8ca
